apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: luismagerre-com-tls
spec:
  secretName: luismagerre-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: luismagerre.com
  dnsNames:
    - luismagerre.com
    - www.luismagerre.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - luismagerre.com
          - www.luismagerre.com
